/**
 * PrestaShop Resource Schemas
 * Auto-generated from PrestaShop API
 * Generated on: 2025-10-30T22:31:03.623Z
 * 
 * This file contains type definitions for all PrestaShop resources
 * Used for automatic type conversion and field validation
 */

export interface FieldSchema {
  type: 'string' | 'number' | 'boolean';
  format: string;
  required: boolean;
  readOnly: boolean;
  multilang: boolean;
  maxSize: number | null;
}

export interface ResourceSchema {
  [fieldName: string]: FieldSchema;
}

export const RESOURCE_SCHEMAS: { [resource: string]: ResourceSchema } = {
  'products': {
    'id_manufacturer': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_supplier': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_category_default': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_tax_rules_group': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_shop_default': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reference': {
      type: 'string',
      format: 'isReference',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 64,
    },
    'supplier_reference': {
      type: 'string',
      format: 'isReference',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 64,
    },
    'location': {
      type: 'string',
      format: 'isString',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'width': {
      type: 'number',
      format: 'isUnsignedFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'height': {
      type: 'number',
      format: 'isUnsignedFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'depth': {
      type: 'number',
      format: 'isUnsignedFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'weight': {
      type: 'number',
      format: 'isUnsignedFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'quantity_discount': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'ean13': {
      type: 'string',
      format: 'isEan13',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 13,
    },
    'isbn': {
      type: 'string',
      format: 'isIsbn',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 32,
    },
    'upc': {
      type: 'string',
      format: 'isUpc',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 12,
    },
    'mpn': {
      type: 'string',
      format: 'isMpn',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 40,
    },
    'cache_is_pack': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'cache_has_attachments': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'is_virtual': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'state': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'additional_delivery_times': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'delivery_in_stock': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'delivery_out_stock': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'product_type': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'on_sale': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'online_only': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'ecotax': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'minimal_quantity': {
      type: 'number',
      format: 'isPositiveInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'low_stock_threshold': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'low_stock_alert': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'price': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'wholesale_price': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'unity': {
      type: 'string',
      format: 'isString',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'unit_price': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'additional_shipping_cost': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'customizable': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'text_fields': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'uploadable_files': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'active': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'redirect_type': {
      type: 'string',
      format: 'isString',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_type_redirected': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'available_for_order': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'available_date': {
      type: 'string',
      format: 'isDateFormat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'show_condition': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'condition': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'show_price': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'indexed': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'visibility': {
      type: 'string',
      format: 'isProductVisibility',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'advanced_stock_management': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_upd': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'pack_stock_type': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'meta_description': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 512,
    },
    'meta_keywords': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'meta_title': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'link_rewrite': {
      type: 'string',
      format: 'isLinkRewrite',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 128,
    },
    'name': {
      type: 'string',
      format: 'isCatalogName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 128,
    },
    'description': {
      type: 'string',
      format: 'isCleanHtml',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 4194303,
    },
    'description_short': {
      type: 'string',
      format: 'isCleanHtml',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 4194303,
    },
    'available_now': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'available_later': {
      type: 'string',
      format: 'IsGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
  },
  'categories': {
    'id_parent': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'level_depth': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'active': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_shop_default': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'is_root_category': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_upd': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'name': {
      type: 'string',
      format: 'isCatalogName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 128,
    },
    'link_rewrite': {
      type: 'string',
      format: 'isLinkRewrite',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 128,
    },
    'description': {
      type: 'string',
      format: 'isCleanHtml',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 4194303,
    },
    'additional_description': {
      type: 'string',
      format: 'isCleanHtml',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 4194303,
    },
    'meta_title': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'meta_description': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 512,
    },
    'meta_keywords': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
  },
  'customers': {
    'id_lang': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'secure_key': {
      type: 'string',
      format: 'isMd5',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'deleted': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'passwd': {
      type: 'string',
      format: 'isHashedPassword',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'lastname': {
      type: 'string',
      format: 'isCustomerName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'firstname': {
      type: 'string',
      format: 'isCustomerName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'email': {
      type: 'string',
      format: 'isEmail',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'id_gender': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'birthday': {
      type: 'string',
      format: 'isBirthDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'newsletter': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'optin': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'website': {
      type: 'string',
      format: 'isUrl',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'company': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'siret': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'ape': {
      type: 'string',
      format: 'isApe',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'outstanding_allow_amount': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'show_public_prices': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_risk': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'max_payment_days': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'active': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'is_guest': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_shop': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_shop_group': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_upd': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reset_password_token': {
      type: 'string',
      format: 'isSha1',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 40,
    },
    'reset_password_validity': {
      type: 'string',
      format: 'isDateOrNull',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'addresses': {
    'id_customer': {
      type: 'number',
      format: 'isNullOrUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_manufacturer': {
      type: 'number',
      format: 'isNullOrUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_supplier': {
      type: 'number',
      format: 'isNullOrUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_warehouse': {
      type: 'number',
      format: 'isNullOrUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_country': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_state': {
      type: 'number',
      format: 'isNullOrUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'alias': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 32,
    },
    'company': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'lastname': {
      type: 'string',
      format: 'isName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'firstname': {
      type: 'string',
      format: 'isName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'vat_number': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'address1': {
      type: 'string',
      format: 'isAddress',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 128,
    },
    'address2': {
      type: 'string',
      format: 'isAddress',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 128,
    },
    'postcode': {
      type: 'string',
      format: 'isPostCode',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 12,
    },
    'city': {
      type: 'string',
      format: 'isCityName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 64,
    },
    'other': {
      type: 'string',
      format: 'isMessage',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 4194303,
    },
    'phone': {
      type: 'string',
      format: 'isPhoneNumber',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 32,
    },
    'phone_mobile': {
      type: 'string',
      format: 'isPhoneNumber',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 32,
    },
    'dni': {
      type: 'string',
      format: 'isDniLite',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 16,
    },
    'deleted': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_upd': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'countries': {
    'id_zone': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_currency': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'call_prefix': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'iso_code': {
      type: 'string',
      format: 'isLanguageIsoCode',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 3,
    },
    'active': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'contains_states': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'need_identification_number': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'need_zip_code': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'zip_code_format': {
      type: 'string',
      format: 'isZipCodeFormat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'display_tax_label': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 64,
    },
  },
  'states': {
    'id_zone': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_country': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'iso_code': {
      type: 'string',
      format: 'isStateIsoCode',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 7,
    },
    'name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 80,
    },
    'active': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'zones': {
    'name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 64,
    },
    'active': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'taxes': {
    'rate': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'active': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'deleted': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 32,
    },
  },
  'tax_rules': {
    'id_tax_rules_group': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_state': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_country': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'zipcode_from': {
      type: 'string',
      format: 'isPostCode',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'zipcode_to': {
      type: 'string',
      format: 'isPostCode',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_tax': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'behavior': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'description': {
      type: 'string',
      format: 'isString',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'tax_rule_groups': {
    'name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 64,
    },
    'active': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'deleted': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_upd': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'carriers': {
    'deleted': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'is_module': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'name': {
      type: 'string',
      format: 'isCarrierName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 64,
    },
    'active': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'is_free': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'url': {
      type: 'string',
      format: 'isAbsoluteUrl',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'shipping_handling': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'range_behavior': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'shipping_method': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'max_width': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'max_height': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'max_depth': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'max_weight': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'grade': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 1,
    },
    'delay': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 512,
    },
  },
  'suppliers': {
    'name': {
      type: 'string',
      format: 'isCatalogName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 64,
    },
    'active': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_upd': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'description': {
      type: 'string',
      format: 'isCleanHtml',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 4194303,
    },
    'meta_title': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'meta_description': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 512,
    },
    'meta_keywords': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
  },
  'manufacturers': {
    'name': {
      type: 'string',
      format: 'isCatalogName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 64,
    },
    'description': {
      type: 'string',
      format: 'isCleanHtml',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 4194303,
    },
    'short_description': {
      type: 'string',
      format: 'isCleanHtml',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 4194303,
    },
    'meta_title': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'meta_description': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 512,
    },
    'meta_keywords': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'orders': {
    'id_address_delivery': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_address_invoice': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_cart': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_currency': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_lang': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_customer': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_carrier': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'current_state': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'module': {
      type: 'string',
      format: 'isModuleName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_upd': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_shop_group': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_shop': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'secure_key': {
      type: 'string',
      format: 'isMd5',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'payment': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'recyclable': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'gift': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'gift_message': {
      type: 'string',
      format: 'isCleanHtml',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 4194303,
    },
    'mobile_theme': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_discounts': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_discounts_tax_incl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_discounts_tax_excl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_paid': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_paid_tax_incl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_paid_tax_excl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_paid_real': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_products': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_products_wt': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_shipping': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_shipping_tax_incl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_shipping_tax_excl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'carrier_tax_rate': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_wrapping': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_wrapping_tax_incl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_wrapping_tax_excl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'round_mode': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'round_type': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'conversion_rate': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'order_details': {
    'id_order': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_id': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_attribute_id': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_quantity_reinjected': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'group_reduction': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'discount_quantity_applied': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'download_hash': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'download_deadline': {
      type: 'string',
      format: 'isDateFormat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_order_invoice': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_warehouse': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_shop': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_customization': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 4194303,
    },
    'product_quantity': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_quantity_in_stock': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_quantity_return': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_quantity_refunded': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_price': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reduction_percent': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reduction_amount': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reduction_amount_tax_incl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reduction_amount_tax_excl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_quantity_discount': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_ean13': {
      type: 'string',
      format: 'isEan13',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_isbn': {
      type: 'string',
      format: 'isIsbn',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_upc': {
      type: 'string',
      format: 'isUpc',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_mpn': {
      type: 'string',
      format: 'isMpn',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_reference': {
      type: 'string',
      format: 'isReference',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_supplier_reference': {
      type: 'string',
      format: 'isReference',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_weight': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'tax_computation_method': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_tax_rules_group': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'ecotax': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'ecotax_tax_rate': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'download_nb': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'unit_price_tax_incl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'unit_price_tax_excl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_price_tax_incl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_price_tax_excl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_shipping_price_tax_excl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_shipping_price_tax_incl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'purchase_supplier_price': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'original_product_price': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'original_wholesale_price': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_refunded_tax_excl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'total_refunded_tax_incl': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'order_histories': {
    'id_employee': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_order_state': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_order': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'order_states': {
    'unremovable': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'delivery': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'hidden': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'send_email': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'module_name': {
      type: 'string',
      format: 'isModuleName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'invoice': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'color': {
      type: 'string',
      format: 'isColor',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'logable': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'shipped': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'paid': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'pdf_delivery': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'pdf_invoice': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'deleted': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 64,
    },
    'template': {
      type: 'string',
      format: 'isTplName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 64,
    },
  },
  'order_invoices': {
    'id_order': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'number': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'delivery_number': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'delivery_date': {
      type: 'string',
      format: 'isDateFormat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'shop_address': {
      type: 'string',
      format: 'isCleanHtml',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 4194303,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'order_carriers': {
    'id_order': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_carrier': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_order_invoice': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'weight': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'shipping_cost_tax_excl': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'shipping_cost_tax_incl': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'tracking_number': {
      type: 'string',
      format: 'isTrackingNumber',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'carts': {
    'id_address_delivery': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_address_invoice': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_currency': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_customer': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_guest': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_lang': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_shop_group': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_shop': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_carrier': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'recyclable': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'gift': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'gift_message': {
      type: 'string',
      format: 'isCleanHtml',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 4194303,
    },
    'mobile_theme': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'allow_seperated_package': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_upd': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'cart_rules': {
    'id_customer': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_from': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_to': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'description': {
      type: 'string',
      format: 'isCleanHtml',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 4194303,
    },
    'quantity': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'quantity_per_user': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'priority': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'partial_use': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'code': {
      type: 'string',
      format: 'isCleanHtml',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 254,
    },
    'minimum_amount': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'minimum_amount_tax': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'minimum_amount_currency': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'minimum_amount_shipping': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'country_restriction': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'carrier_restriction': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'group_restriction': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'cart_rule_restriction': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'product_restriction': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'shop_restriction': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'free_shipping': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reduction_percent': {
      type: 'string',
      format: 'isPercentage',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reduction_amount': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reduction_tax': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reduction_currency': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reduction_product': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reduction_exclude_special': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'gift_product': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'gift_product_attribute': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'highlight': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'active': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_upd': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'currencies': {
    'name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'iso_code': {
      type: 'string',
      format: 'isLanguageIsoCode',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 3,
    },
    'numeric_iso_code': {
      type: 'string',
      format: 'isNumericIsoCode',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 3,
    },
    'precision': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'conversion_rate': {
      type: 'number',
      format: 'isUnsignedFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'deleted': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'active': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'unofficial': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'modified': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'languages': {
    'name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 32,
    },
    'iso_code': {
      type: 'string',
      format: 'isLanguageIsoCode',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 2,
    },
    'locale': {
      type: 'string',
      format: 'isLocale',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 5,
    },
    'language_code': {
      type: 'string',
      format: 'isLanguageCode',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 5,
    },
    'active': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'is_rtl': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_format_lite': {
      type: 'string',
      format: 'isPhpDateFormat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 32,
    },
    'date_format_full': {
      type: 'string',
      format: 'isPhpDateFormat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 32,
    },
  },
  'groups': {
    'reduction': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'price_display_method': {
      type: 'string',
      format: 'isPriceDisplayMethod',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'show_prices': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_upd': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 32,
    },
  },
  'stock_availables': {
    'id_product': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_product_attribute': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_shop': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_shop_group': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'quantity': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'depends_on_stock': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'out_of_stock': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'location': {
      type: 'string',
      format: 'isString',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
  },
  'stocks': {
    'id_warehouse': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_product': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_product_attribute': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reference': {
      type: 'string',
      format: 'isReference',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'ean13': {
      type: 'string',
      format: 'isEan13',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'isbn': {
      type: 'string',
      format: 'isIsbn',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'upc': {
      type: 'string',
      format: 'isUpc',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'mpn': {
      type: 'string',
      format: 'isMpn',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'physical_quantity': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'usable_quantity': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'price_te': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'stock_movements': {
    'id_employee': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_stock': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_stock_mvt_reason': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_order': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_supply_order': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'physical_quantity': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'sign': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'last_wa': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'current_wa': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'price_te': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'combinations': {
    'id_product': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'ean13': {
      type: 'string',
      format: 'isEan13',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 13,
    },
    'isbn': {
      type: 'string',
      format: 'isIsbn',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 32,
    },
    'upc': {
      type: 'string',
      format: 'isUpc',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 12,
    },
    'mpn': {
      type: 'string',
      format: 'isMpn',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 40,
    },
    'wholesale_price': {
      type: 'string',
      format: 'isNegativePrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 27,
    },
    'price': {
      type: 'string',
      format: 'isNegativePrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 20,
    },
    'ecotax': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 20,
    },
    'weight': {
      type: 'number',
      format: 'isFloat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'unit_price_impact': {
      type: 'string',
      format: 'isNegativePrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 20,
    },
    'minimal_quantity': {
      type: 'number',
      format: 'isPositiveInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'low_stock_threshold': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'low_stock_alert': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'default_on': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'available_date': {
      type: 'string',
      format: 'isDateFormat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'available_now': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'available_later': {
      type: 'string',
      format: 'IsGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
  },
  'tags': {
    'id_lang': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 32,
    },
  },
  'specific_prices': {
    'id_shop_group': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_shop': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_cart': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_product': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_product_attribute': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_currency': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_country': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_group': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_customer': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_specific_price_rule': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'price': {
      type: 'string',
      format: 'isNegativePrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'from_quantity': {
      type: 'number',
      format: 'isUnsignedInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reduction': {
      type: 'number',
      format: 'isPrice',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reduction_tax': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'reduction_type': {
      type: 'string',
      format: 'isReductionType',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'from': {
      type: 'string',
      format: 'isDateFormat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'to': {
      type: 'string',
      format: 'isDateFormat',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'product_options': {
    'is_color_group': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'position': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 128,
    },
    'public_name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 64,
    },
  },
  'customer_threads': {
    'id_lang': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_shop': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_customer': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_order': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_product': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_contact': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'email': {
      type: 'string',
      format: 'isEmail',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
    'token': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_upd': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'customer_messages': {
    'id_employee': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'ip_address': {
      type: 'string',
      format: 'isIp2Long',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 15,
    },
    'message': {
      type: 'string',
      format: 'isCleanHtml',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 4194303,
    },
    'private': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_add': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'date_upd': {
      type: 'string',
      format: 'isDate',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'read': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
  'product_features': {
    'position': {
      type: 'number',
      format: 'isInt',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 128,
    },
  },
  'product_feature_values': {
    'id_feature': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'custom': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'value': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 255,
    },
  },
  'shops': {
    'id_shop_group': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'id_category': {
      type: 'number',
      format: 'isUnsignedId',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'active': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'deleted': {
      type: 'boolean',
      format: 'isBool',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'name': {
      type: 'string',
      format: 'isGenericName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: 64,
    },
    'color': {
      type: 'string',
      format: 'isColor',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
    'theme_name': {
      type: 'string',
      format: 'isThemeName',
      required: false,
      readOnly: false,
      multilang: false,
      maxSize: null,
    },
  },
};

/**
 * Get schema for a specific resource
 */
export function getResourceSchema(resource: string): ResourceSchema | null {
  return RESOURCE_SCHEMAS[resource] || null;
}

/**
 * Get all field names for a resource
 */
export function getResourceFields(resource: string): string[] {
  const schema = getResourceSchema(resource);
  return schema ? Object.keys(schema) : [];
}

/**
 * Get required fields for a resource
 */
export function getRequiredFields(resource: string): string[] {
  const schema = getResourceSchema(resource);
  if (!schema) return [];
  
  return Object.entries(schema)
    .filter(([_, info]) => info.required)
    .map(([field, _]) => field);
}

/**
 * Get writable fields for a resource (not read-only)
 */
export function getWritableFields(resource: string): string[] {
  const schema = getResourceSchema(resource);
  if (!schema) return [];
  
  return Object.entries(schema)
    .filter(([_, info]) => !info.readOnly)
    .map(([field, _]) => field);
}

/**
 * Convert field value to correct type based on schema
 */
export function convertFieldValue(value: any, fieldInfo: FieldSchema): any {
  if (value === null || value === undefined || value === '') {
    return value;
  }

  switch (fieldInfo.type) {
    case 'number':
      const num = Number(value);
      return isNaN(num) ? value : num;
    
    case 'boolean':
      if (typeof value === 'boolean') return value;
      if (value === '1' || value === 1) return true;
      if (value === '0' || value === 0) return false;
      return Boolean(value);
    
    case 'string':
    default:
      return String(value);
  }
}

/**
 * Convert all fields in an object based on resource schema
 */
export function convertResourceTypes(data: any, resource: string): any {
  const schema = getResourceSchema(resource);
  if (!schema || !data || typeof data !== 'object') {
    return data;
  }

  const converted: any = {};

  for (const [field, value] of Object.entries(data)) {
    if (schema[field]) {
      converted[field] = convertFieldValue(value, schema[field]);
    } else {
      // Keep fields not in schema as-is
      converted[field] = value;
    }
  }

  return converted;
}

/**
 * Convert array of resources
 */
export function convertResourceArray(data: any[], resource: string): any[] {
  if (!Array.isArray(data)) return data;
  return data.map(item => convertResourceTypes(item, resource));
}
